modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT"
issueTrackerURL="https://github.com/quinn-semele/aoe-emotes/issues/"

[[mods]]
modId="aoeemotes"
version="${mod_version}"
displayName="AOE Emotes"
displayURL="https://www.curseforge.com/minecraft/mc-mods/aof-emotes/"
logoFile="aoe-emotes.png"
authors="AlgidSpace, Team AOE"
description="Discord style chat emotes for Minecraft chat. A fork of Fabric Emotes."

[[mixins]]
config="aoe-emotes.mixins.json"

[[dependencies.aofemotes]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="CLIENT"

[[dependencies.aofemotes]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="CLIENT"
